---
roles:
  compile_master_puppetdb_node_group:
    provisioners:
      - type: shell
        inline: "puppet apply /vagrant/puppet_code/create_compile_master_pdb_node_group.pp --modulepath /opt/puppetlabs/server/data/enterprise/modules/"

  external_postgres_pe_conf:
    provisioners:
      - type: pe_bootstrap
        answer_file: 'answer_files/pe.conf'

  blank_resolve_conf:
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"

  pe_agent:
    provisioners:
      - type: pe_agent
        master: 'pe-mom'
