---
vms:
  - name: "pe-mom"
    box:  "puppetlabs/centos-6.6-64-nocm"
    roles:
      - "compile_master_puppetdb_node_group"
      - "external_postgres_pe_conf"
      - "customize_pe_via_hiera_2015"
      - "blank_resolve_conf"
      - "4-cpus"
      - "2gb-memory"
      - "centos"
      - "hosts"
      - "auto_net"

  - name: "external-postgres"
    box:  "puppetlabs/centos-6.6-64-nocm"
    roles:
      - "external_postgres_pe_conf"
      - "blank_resolve_conf"
      - "4-cpus"
      - "2gb-memory"
      - "centos"
      - "hosts"
      - "auto_net"

  - name: "compile-master-puppetdb"
    box:  "puppetlabs/centos-6.6-64-nocm"
    roles:
      - "customize_pe_via_hiera_2015"
      - "pe_agent"
      - "4-cpus"
      - "2gb-memory"
      - "centos"
      - "hosts"
      - "auto_net"

